### ISSUE TITLE
Configurable language code mapping between MS and Transifex language codes

### ISSUE THREAD

**Issue by tsido** [futurice/grunt-transifex-resjson#12]
There are some differences between language codes used in Transifex (https://www.transifex.com/languages/) and in Microsoft  (http://msdn.microsoft.com/en-gb/library/windows/apps/jj657969.aspx) that can cause trouble when uploading/downloading translation resources to/from Transifex.

Currently the language codes are automatically converted from local form to Transifex style assuming that the code is in either of form  `xx_YY` or `xx-latn` and converted to `xx-YY` or `xy@latin`. However, there's bunch of other cases that should be taken care of.

Additionally and maybe more importantly we could use with support for defining mapping between the local and Transifex language codes in the config file. If such optional mapping is found for a local language code then that would be used instead of the automatic mapping. This can become handy as the lang codes used Transifex and locally can differ because of various reasons.

**Comment by rymai** [comment]
Hi, I'm in favor of allowing languages code in the form of `[a-z]{2,3}` since they're [supported by Transifex](https://www.transifex.com/languages/). This could be a really simple first step.

Right now, I have to set `en_US` as my source language but I'd prefer simply `en`...

I'll propose a PR!
